### ISSUE TITLE
mobile training 向け教材のURLが missing

### ISSUE THREAD

**Issue by iwashi** [pepabo/training#9]
https://github.com/pepabo/training/blob/325cdf5737590897e36cb458c4e864188773e422/mobile-training/README.md?plain=1#L3

上記のテキストへのURLが 404 応答となっているようです。

**Comment by june29** [comment]
ご報告ありがとうございました :pray:
ずいぶんと時間が経ってしまいましたが、先ほど手を入れました :dash:
